export interface Product {
  id: string;
  name: string;
  price: number;
  imageUrl: string;
  category: "beauty" | "herbal" | "food" | "textiles";
  description?: string;
  uses?: string;
  data?: string;
  whyToUse?: string;
  howToUse?: string;
  boughtLastMonth?: number;
  isTrending?: boolean;
  isRecommended?: boolean;
}

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "b1",
    name: "Radiant Skin Serum",
    price: 45.0,
    category: "beauty",
    imageUrl: "/images/beauty_serum.png",
    boughtLastMonth: 1087,
    isTrending: false,
    isRecommended: true,
    description: "The Radiant Skin Serum is a premium, dermatologist-tested formula designed to nourish and revitalize. Crafted with clinically proven active ingredients, it deeply hydrates and restores your skin's natural barrier.",
    uses: "Perfect for daily skincare routines. Helps combat dryness, uneven texture, and dullness while providing a smooth, radiant finish.",
    data: "100% Vegan • Cruelty-Free • Paraben-Free • Dermatologist Approved",
    whyToUse: "Unlike harsh chemical alternatives, this product uses bio-compatible ingredients that your skin easily absorbs, ensuring faster and more noticeable results without irritation.",
    howToUse: "Apply a small amount to clean, dry skin. Gently massage in upward circular motions until fully absorbed. Use morning and night for best results.",
  },
  {
    id: "b2",
    name: "Hydrating Face Cream",
    price: 32.5,
    category: "beauty",
    imageUrl: "/images/beauty_cream.png",
    boughtLastMonth: 929,
    isTrending: false,
    isRecommended: true,
    description: "The Hydrating Face Cream is a premium, dermatologist-tested formula designed to nourish and revitalize. Crafted with clinically proven active ingredients, it deeply hydrates and restores your skin's natural barrier.",
    uses: "Perfect for daily skincare routines. Helps combat dryness, uneven texture, and dullness while providing a smooth, radiant finish.",
    data: "100% Vegan • Cruelty-Free • Paraben-Free • Dermatologist Approved",
    whyToUse: "Unlike harsh chemical alternatives, this product uses bio-compatible ingredients that your skin easily absorbs, ensuring faster and more noticeable results without irritation.",
    howToUse: "Apply a small amount to clean, dry skin. Gently massage in upward circular motions until fully absorbed. Use morning and night for best results.",
  },
  {
    id: "b3",
    name: "Vitamin C Brightening Drops",
    price: 38.0,
    category: "beauty",
    imageUrl: "/images/beauty_vitamin_c.png",
    boughtLastMonth: 3750,
    isTrending: true,
    isRecommended: true,
    description: "The Vitamin C Brightening Drops is a premium, dermatologist-tested formula designed to nourish and revitalize. Crafted with clinically proven active ingredients, it deeply hydrates and restores your skin's natural barrier.",
    uses: "Perfect for daily skincare routines. Helps combat dryness, uneven texture, and dullness while providing a smooth, radiant finish.",
    data: "100% Vegan • Cruelty-Free • Paraben-Free • Dermatologist Approved",
    whyToUse: "Unlike harsh chemical alternatives, this product uses bio-compatible ingredients that your skin easily absorbs, ensuring faster and more noticeable results without irritation.",
    howToUse: "Apply a small amount to clean, dry skin. Gently massage in upward circular motions until fully absorbed. Use morning and night for best results.",
  },
  {
    id: "b4",
    name: "Purifying Clay Mask",
    price: 28.0,
    category: "beauty",
    imageUrl: "/images/beauty_clay_mask.png",
    boughtLastMonth: 2786,
    isTrending: true,
    isRecommended: false,
    description: "The Purifying Clay Mask is a premium, dermatologist-tested formula designed to nourish and revitalize. Crafted with clinically proven active ingredients, it deeply hydrates and restores your skin's natural barrier.",
    uses: "Perfect for daily skincare routines. Helps combat dryness, uneven texture, and dullness while providing a smooth, radiant finish.",
    data: "100% Vegan • Cruelty-Free • Paraben-Free • Dermatologist Approved",
    whyToUse: "Unlike harsh chemical alternatives, this product uses bio-compatible ingredients that your skin easily absorbs, ensuring faster and more noticeable results without irritation.",
    howToUse: "Apply a small amount to clean, dry skin. Gently massage in upward circular motions until fully absorbed. Use morning and night for best results.",
  },
  {
    id: "b5",
    name: "Rosewater Facial Toner",
    price: 22.0,
    category: "beauty",
    imageUrl: "/images/beauty_toner.png",
    boughtLastMonth: 3022,
    isTrending: false,
    isRecommended: false,
    description: "The Rosewater Facial Toner is a premium, dermatologist-tested formula designed to nourish and revitalize. Crafted with clinically proven active ingredients, it deeply hydrates and restores your skin's natural barrier.",
    uses: "Perfect for daily skincare routines. Helps combat dryness, uneven texture, and dullness while providing a smooth, radiant finish.",
    data: "100% Vegan • Cruelty-Free • Paraben-Free • Dermatologist Approved",
    whyToUse: "Unlike harsh chemical alternatives, this product uses bio-compatible ingredients that your skin easily absorbs, ensuring faster and more noticeable results without irritation.",
    howToUse: "Apply a small amount to clean, dry skin. Gently massage in upward circular motions until fully absorbed. Use morning and night for best results.",
  },
  {
    id: "b6",
    name: "Overnight Repair Night Cream",
    price: 55.0,
    category: "beauty",
    imageUrl: "/images/beauty_night_cream.png",
    boughtLastMonth: 1394,
    isTrending: false,
    isRecommended: false,
    description: "The Overnight Repair Night Cream is a premium, dermatologist-tested formula designed to nourish and revitalize. Crafted with clinically proven active ingredients, it deeply hydrates and restores your skin's natural barrier.",
    uses: "Perfect for daily skincare routines. Helps combat dryness, uneven texture, and dullness while providing a smooth, radiant finish.",
    data: "100% Vegan • Cruelty-Free • Paraben-Free • Dermatologist Approved",
    whyToUse: "Unlike harsh chemical alternatives, this product uses bio-compatible ingredients that your skin easily absorbs, ensuring faster and more noticeable results without irritation.",
    howToUse: "Apply a small amount to clean, dry skin. Gently massage in upward circular motions until fully absorbed. Use morning and night for best results.",
  },
  {
    id: "b7",
    name: "Gentle Foaming Cleanser",
    price: 26.0,
    category: "beauty",
    imageUrl: "/images/beauty_cleanser.png",
    boughtLastMonth: 887,
    isTrending: false,
    isRecommended: false,
    description: "The Gentle Foaming Cleanser is a premium, dermatologist-tested formula designed to nourish and revitalize. Crafted with clinically proven active ingredients, it deeply hydrates and restores your skin's natural barrier.",
    uses: "Perfect for daily skincare routines. Helps combat dryness, uneven texture, and dullness while providing a smooth, radiant finish.",
    data: "100% Vegan • Cruelty-Free • Paraben-Free • Dermatologist Approved",
    whyToUse: "Unlike harsh chemical alternatives, this product uses bio-compatible ingredients that your skin easily absorbs, ensuring faster and more noticeable results without irritation.",
    howToUse: "Apply a small amount to clean, dry skin. Gently massage in upward circular motions until fully absorbed. Use morning and night for best results.",
  },
  {
    id: "b8",
    name: "Exfoliating Walnut Scrub",
    price: 30.0,
    category: "beauty",
    imageUrl: "/images/beauty_scrub.png",
    boughtLastMonth: 3917,
    isTrending: true,
    isRecommended: true,
    description: "The Exfoliating Walnut Scrub is a premium, dermatologist-tested formula designed to nourish and revitalize. Crafted with clinically proven active ingredients, it deeply hydrates and restores your skin's natural barrier.",
    uses: "Perfect for daily skincare routines. Helps combat dryness, uneven texture, and dullness while providing a smooth, radiant finish.",
    data: "100% Vegan • Cruelty-Free • Paraben-Free • Dermatologist Approved",
    whyToUse: "Unlike harsh chemical alternatives, this product uses bio-compatible ingredients that your skin easily absorbs, ensuring faster and more noticeable results without irritation.",
    howToUse: "Apply a small amount to clean, dry skin. Gently massage in upward circular motions until fully absorbed. Use morning and night for best results.",
  },
  {
    id: "b9",
    name: "Hyaluronic Acid Gel",
    price: 42.0,
    category: "beauty",
    imageUrl: "/images/beauty_hyaluronic.png",
    boughtLastMonth: 2012,
    isTrending: true,
    isRecommended: true,
    description: "The Hyaluronic Acid Gel is a premium, dermatologist-tested formula designed to nourish and revitalize. Crafted with clinically proven active ingredients, it deeply hydrates and restores your skin's natural barrier.",
    uses: "Perfect for daily skincare routines. Helps combat dryness, uneven texture, and dullness while providing a smooth, radiant finish.",
    data: "100% Vegan • Cruelty-Free • Paraben-Free • Dermatologist Approved",
    whyToUse: "Unlike harsh chemical alternatives, this product uses bio-compatible ingredients that your skin easily absorbs, ensuring faster and more noticeable results without irritation.",
    howToUse: "Apply a small amount to clean, dry skin. Gently massage in upward circular motions until fully absorbed. Use morning and night for best results.",
  },
  {
    id: "b10",
    name: "Revitalizing Eye Cream",
    price: 36.0,
    category: "beauty",
    imageUrl: "/images/beauty_eye_cream.png",
    boughtLastMonth: 357,
    isTrending: true,
    isRecommended: false,
    description: "The Revitalizing Eye Cream is a premium, dermatologist-tested formula designed to nourish and revitalize. Crafted with clinically proven active ingredients, it deeply hydrates and restores your skin's natural barrier.",
    uses: "Perfect for daily skincare routines. Helps combat dryness, uneven texture, and dullness while providing a smooth, radiant finish.",
    data: "100% Vegan • Cruelty-Free • Paraben-Free • Dermatologist Approved",
    whyToUse: "Unlike harsh chemical alternatives, this product uses bio-compatible ingredients that your skin easily absorbs, ensuring faster and more noticeable results without irritation.",
    howToUse: "Apply a small amount to clean, dry skin. Gently massage in upward circular motions until fully absorbed. Use morning and night for best results.",
  },
  {
    id: "h1",
    name: "Akschan Ashwagandha Extract",
    price: 24.0,
    category: "herbal",
    imageUrl: "/images/herbal_ashwagandha.png",
    boughtLastMonth: 2707,
    isTrending: false,
    isRecommended: true,
    description: "Akschan Ashwagandha Extract is a potent, traditionally sourced supplement that brings ancient Ayurvedic wisdom into modern wellness. Made from pure, potent botanical extracts.",
    uses: "Ideal for balancing natural body systems, supporting immunity, and promoting holistic well-being.",
    data: "USDA Organic • Non-GMO • Sustainably Wildcrafted • 100% Pure Extract",
    whyToUse: "Sourced directly from organic farms, ensuring maximum potency and purity. Free from fillers, artificial preservatives, and synthetic binders.",
    howToUse: "Take the recommended dosage with warm water or milk, preferably after meals. Consult your healthcare provider before starting any new herbal regimen.",
  },
  {
    id: "h2",
    name: "Akschan Turmeric Curcumin",
    price: 18.0,
    category: "herbal",
    imageUrl: "/images/herbal_turmeric.png",
    boughtLastMonth: 2702,
    isTrending: false,
    isRecommended: true,
    description: "Akschan Turmeric Curcumin is a potent, traditionally sourced supplement that brings ancient Ayurvedic wisdom into modern wellness. Made from pure, potent botanical extracts.",
    uses: "Ideal for balancing natural body systems, supporting immunity, and promoting holistic well-being.",
    data: "USDA Organic • Non-GMO • Sustainably Wildcrafted • 100% Pure Extract",
    whyToUse: "Sourced directly from organic farms, ensuring maximum potency and purity. Free from fillers, artificial preservatives, and synthetic binders.",
    howToUse: "Take the recommended dosage with warm water or milk, preferably after meals. Consult your healthcare provider before starting any new herbal regimen.",
  },
  {
    id: "h3",
    name: "Akschan Natural Haircare Oil",
    price: 35.0,
    category: "herbal",
    imageUrl: "/images/herbal_haircare_oil.png",
    boughtLastMonth: 1905,
    isTrending: true,
    isRecommended: true,
    description: "Akschan Natural Haircare Oil is a potent, traditionally sourced supplement that brings ancient Ayurvedic wisdom into modern wellness. Made from pure, potent botanical extracts.",
    uses: "Ideal for balancing natural body systems, supporting immunity, and promoting holistic well-being.",
    data: "USDA Organic • Non-GMO • Sustainably Wildcrafted • 100% Pure Extract",
    whyToUse: "Sourced directly from organic farms, ensuring maximum potency and purity. Free from fillers, artificial preservatives, and synthetic binders.",
    howToUse: "Take the recommended dosage with warm water or milk, preferably after meals. Consult your healthcare provider before starting any new herbal regimen.",
  },
  {
    id: "h4",
    name: "Akschan Herbal Skincare Cream",
    price: 29.0,
    category: "herbal",
    imageUrl: "/images/herbal_skincare_cream.png",
    boughtLastMonth: 619,
    isTrending: true,
    isRecommended: true,
    description: "Akschan Herbal Skincare Cream is a potent, traditionally sourced supplement that brings ancient Ayurvedic wisdom into modern wellness. Made from pure, potent botanical extracts.",
    uses: "Ideal for balancing natural body systems, supporting immunity, and promoting holistic well-being.",
    data: "USDA Organic • Non-GMO • Sustainably Wildcrafted • 100% Pure Extract",
    whyToUse: "Sourced directly from organic farms, ensuring maximum potency and purity. Free from fillers, artificial preservatives, and synthetic binders.",
    howToUse: "Take the recommended dosage with warm water or milk, preferably after meals. Consult your healthcare provider before starting any new herbal regimen.",
  },
  {
    id: "h5",
    name: "Akschan Scalp Nourishment Serum",
    price: 32.0,
    category: "herbal",
    imageUrl: "/images/herbal_scalp_serum.png",
    boughtLastMonth: 2828,
    isTrending: false,
    isRecommended: true,
    description: "Akschan Scalp Nourishment Serum is a potent, traditionally sourced supplement that brings ancient Ayurvedic wisdom into modern wellness. Made from pure, potent botanical extracts.",
    uses: "Ideal for balancing natural body systems, supporting immunity, and promoting holistic well-being.",
    data: "USDA Organic • Non-GMO • Sustainably Wildcrafted • 100% Pure Extract",
    whyToUse: "Sourced directly from organic farms, ensuring maximum potency and purity. Free from fillers, artificial preservatives, and synthetic binders.",
    howToUse: "Take the recommended dosage with warm water or milk, preferably after meals. Consult your healthcare provider before starting any new herbal regimen.",
  },
  {
    id: "h6",
    name: "Akschan Brahmi Brain Tonic",
    price: 26.0,
    category: "herbal",
    imageUrl: "/images/herbal_brain_tonic.png",
    boughtLastMonth: 2332,
    isTrending: false,
    isRecommended: true,
    description: "Akschan Brahmi Brain Tonic is a potent, traditionally sourced supplement that brings ancient Ayurvedic wisdom into modern wellness. Made from pure, potent botanical extracts.",
    uses: "Ideal for balancing natural body systems, supporting immunity, and promoting holistic well-being.",
    data: "USDA Organic • Non-GMO • Sustainably Wildcrafted • 100% Pure Extract",
    whyToUse: "Sourced directly from organic farms, ensuring maximum potency and purity. Free from fillers, artificial preservatives, and synthetic binders.",
    howToUse: "Take the recommended dosage with warm water or milk, preferably after meals. Consult your healthcare provider before starting any new herbal regimen.",
  },
  {
    id: "h7",
    name: "Akschan Neem Purifying Wash",
    price: 21.0,
    category: "herbal",
    imageUrl: "/images/herbal_neem_wash.png",
    boughtLastMonth: 1055,
    isTrending: false,
    isRecommended: true,
    description: "Akschan Neem Purifying Wash is a potent, traditionally sourced supplement that brings ancient Ayurvedic wisdom into modern wellness. Made from pure, potent botanical extracts.",
    uses: "Ideal for balancing natural body systems, supporting immunity, and promoting holistic well-being.",
    data: "USDA Organic • Non-GMO • Sustainably Wildcrafted • 100% Pure Extract",
    whyToUse: "Sourced directly from organic farms, ensuring maximum potency and purity. Free from fillers, artificial preservatives, and synthetic binders.",
    howToUse: "Take the recommended dosage with warm water or milk, preferably after meals. Consult your healthcare provider before starting any new herbal regimen.",
  },
  {
    id: "h8",
    name: "Akschan Triphala Digest",
    price: 19.5,
    category: "herbal",
    imageUrl: "/images/herbal_triphala.png",
    boughtLastMonth: 2756,
    isTrending: false,
    isRecommended: true,
    description: "Akschan Triphala Digest is a potent, traditionally sourced supplement that brings ancient Ayurvedic wisdom into modern wellness. Made from pure, potent botanical extracts.",
    uses: "Ideal for balancing natural body systems, supporting immunity, and promoting holistic well-being.",
    data: "USDA Organic • Non-GMO • Sustainably Wildcrafted • 100% Pure Extract",
    whyToUse: "Sourced directly from organic farms, ensuring maximum potency and purity. Free from fillers, artificial preservatives, and synthetic binders.",
    howToUse: "Take the recommended dosage with warm water or milk, preferably after meals. Consult your healthcare provider before starting any new herbal regimen.",
  },
  {
    id: "h9",
    name: "Akschan Tulsi Immunity Drops",
    price: 25.0,
    category: "herbal",
    imageUrl: "/images/herbal_immunity_drops.png",
    boughtLastMonth: 355,
    isTrending: true,
    isRecommended: false,
    description: "Akschan Tulsi Immunity Drops is a potent, traditionally sourced supplement that brings ancient Ayurvedic wisdom into modern wellness. Made from pure, potent botanical extracts.",
    uses: "Ideal for balancing natural body systems, supporting immunity, and promoting holistic well-being.",
    data: "USDA Organic • Non-GMO • Sustainably Wildcrafted • 100% Pure Extract",
    whyToUse: "Sourced directly from organic farms, ensuring maximum potency and purity. Free from fillers, artificial preservatives, and synthetic binders.",
    howToUse: "Take the recommended dosage with warm water or milk, preferably after meals. Consult your healthcare provider before starting any new herbal regimen.",
  },
  {
    id: "h10",
    name: "Akschan Amla Vitamin C Pure",
    price: 22.0,
    category: "herbal",
    imageUrl: "/images/herbal_amla_pure.png",
    boughtLastMonth: 1619,
    isTrending: true,
    isRecommended: false,
    description: "Akschan Amla Vitamin C Pure is a potent, traditionally sourced supplement that brings ancient Ayurvedic wisdom into modern wellness. Made from pure, potent botanical extracts.",
    uses: "Ideal for balancing natural body systems, supporting immunity, and promoting holistic well-being.",
    data: "USDA Organic • Non-GMO • Sustainably Wildcrafted • 100% Pure Extract",
    whyToUse: "Sourced directly from organic farms, ensuring maximum potency and purity. Free from fillers, artificial preservatives, and synthetic binders.",
    howToUse: "Take the recommended dosage with warm water or milk, preferably after meals. Consult your healthcare provider before starting any new herbal regimen.",
  },
  {
    id: "f1",
    name: "Organic Honey",
    price: 12.0,
    category: "food",
    imageUrl: "/images/food_honey.png",
    boughtLastMonth: 2427,
    isTrending: true,
    isRecommended: true,
    description: "Our Organic Honey is a culinary delight, sourced from the finest ethical farms around the globe. Rich in authentic flavor and packed with natural nutrients.",
    uses: "A versatile ingredient perfect for elevating your daily meals, baking, or enjoying straight from the source.",
    data: "Certified Organic • Ethically Sourced • No Added Preservatives • Nutrient Dense",
    whyToUse: "We work directly with farmers to ensure fair trade practices while bringing you the highest quality, unadulterated ingredients that taste better and are better for you.",
    howToUse: "Store in a cool, dry place. Use as desired in your favorite recipes to add a touch of premium, natural flavor.",
  },
  {
    id: "f2",
    name: "Premium Saffron",
    price: 65.0,
    category: "food",
    imageUrl: "/images/food_saffron.png",
    boughtLastMonth: 2037,
    isTrending: false,
    isRecommended: true,
    description: "Our Premium Saffron is a culinary delight, sourced from the finest ethical farms around the globe. Rich in authentic flavor and packed with natural nutrients.",
    uses: "A versatile ingredient perfect for elevating your daily meals, baking, or enjoying straight from the source.",
    data: "Certified Organic • Ethically Sourced • No Added Preservatives • Nutrient Dense",
    whyToUse: "We work directly with farmers to ensure fair trade practices while bringing you the highest quality, unadulterated ingredients that taste better and are better for you.",
    howToUse: "Store in a cool, dry place. Use as desired in your favorite recipes to add a touch of premium, natural flavor.",
  },
  {
    id: "f3",
    name: "Himalayan Pink Salt",
    price: 14.5,
    category: "food",
    imageUrl: "/images/food_pink_salt.png",
    boughtLastMonth: 977,
    isTrending: false,
    isRecommended: true,
    description: "Our Himalayan Pink Salt is a culinary delight, sourced from the finest ethical farms around the globe. Rich in authentic flavor and packed with natural nutrients.",
    uses: "A versatile ingredient perfect for elevating your daily meals, baking, or enjoying straight from the source.",
    data: "Certified Organic • Ethically Sourced • No Added Preservatives • Nutrient Dense",
    whyToUse: "We work directly with farmers to ensure fair trade practices while bringing you the highest quality, unadulterated ingredients that taste better and are better for you.",
    howToUse: "Store in a cool, dry place. Use as desired in your favorite recipes to add a touch of premium, natural flavor.",
  },
  {
    id: "f4",
    name: "Organic Chia Seeds",
    price: 10.0,
    category: "food",
    imageUrl: "/images/food_chia_seeds.png",
    boughtLastMonth: 972,
    isTrending: true,
    isRecommended: true,
    description: "Our Organic Chia Seeds is a culinary delight, sourced from the finest ethical farms around the globe. Rich in authentic flavor and packed with natural nutrients.",
    uses: "A versatile ingredient perfect for elevating your daily meals, baking, or enjoying straight from the source.",
    data: "Certified Organic • Ethically Sourced • No Added Preservatives • Nutrient Dense",
    whyToUse: "We work directly with farmers to ensure fair trade practices while bringing you the highest quality, unadulterated ingredients that taste better and are better for you.",
    howToUse: "Store in a cool, dry place. Use as desired in your favorite recipes to add a touch of premium, natural flavor.",
  },
  {
    id: "f5",
    name: "Cold-Pressed Olive Oil",
    price: 24.0,
    category: "food",
    imageUrl: "/images/food_olive_oil.png",
    boughtLastMonth: 3948,
    isTrending: false,
    isRecommended: true,
    description: "Our Cold-Pressed Olive Oil is a culinary delight, sourced from the finest ethical farms around the globe. Rich in authentic flavor and packed with natural nutrients.",
    uses: "A versatile ingredient perfect for elevating your daily meals, baking, or enjoying straight from the source.",
    data: "Certified Organic • Ethically Sourced • No Added Preservatives • Nutrient Dense",
    whyToUse: "We work directly with farmers to ensure fair trade practices while bringing you the highest quality, unadulterated ingredients that taste better and are better for you.",
    howToUse: "Store in a cool, dry place. Use as desired in your favorite recipes to add a touch of premium, natural flavor.",
  },
  {
    id: "f6",
    name: "Roasted Almond Butter",
    price: 16.0,
    category: "food",
    imageUrl: "/images/food_almond_butter.png",
    boughtLastMonth: 3404,
    isTrending: false,
    isRecommended: false,
    description: "Our Roasted Almond Butter is a culinary delight, sourced from the finest ethical farms around the globe. Rich in authentic flavor and packed with natural nutrients.",
    uses: "A versatile ingredient perfect for elevating your daily meals, baking, or enjoying straight from the source.",
    data: "Certified Organic • Ethically Sourced • No Added Preservatives • Nutrient Dense",
    whyToUse: "We work directly with farmers to ensure fair trade practices while bringing you the highest quality, unadulterated ingredients that taste better and are better for you.",
    howToUse: "Store in a cool, dry place. Use as desired in your favorite recipes to add a touch of premium, natural flavor.",
  },
  {
    id: "f7",
    name: "Matcha Green Tea Powder",
    price: 28.0,
    category: "food",
    imageUrl: "/images/food_matcha_powder.png",
    boughtLastMonth: 2217,
    isTrending: false,
    isRecommended: true,
    description: "Our Matcha Green Tea Powder is a culinary delight, sourced from the finest ethical farms around the globe. Rich in authentic flavor and packed with natural nutrients.",
    uses: "A versatile ingredient perfect for elevating your daily meals, baking, or enjoying straight from the source.",
    data: "Certified Organic • Ethically Sourced • No Added Preservatives • Nutrient Dense",
    whyToUse: "We work directly with farmers to ensure fair trade practices while bringing you the highest quality, unadulterated ingredients that taste better and are better for you.",
    howToUse: "Store in a cool, dry place. Use as desired in your favorite recipes to add a touch of premium, natural flavor.",
  },
  {
    id: "f8",
    name: "Raw Cacao Nibs",
    price: 18.0,
    category: "food",
    imageUrl: "/images/food_cacao_nibs.png",
    boughtLastMonth: 1451,
    isTrending: false,
    isRecommended: true,
    description: "Our Raw Cacao Nibs is a culinary delight, sourced from the finest ethical farms around the globe. Rich in authentic flavor and packed with natural nutrients.",
    uses: "A versatile ingredient perfect for elevating your daily meals, baking, or enjoying straight from the source.",
    data: "Certified Organic • Ethically Sourced • No Added Preservatives • Nutrient Dense",
    whyToUse: "We work directly with farmers to ensure fair trade practices while bringing you the highest quality, unadulterated ingredients that taste better and are better for you.",
    howToUse: "Store in a cool, dry place. Use as desired in your favorite recipes to add a touch of premium, natural flavor.",
  },
  {
    id: "f9",
    name: "Organic Quinoa",
    price: 11.5,
    category: "food",
    imageUrl: "/images/food_quinoa.png",
    boughtLastMonth: 1224,
    isTrending: false,
    isRecommended: false,
    description: "Our Organic Quinoa is a culinary delight, sourced from the finest ethical farms around the globe. Rich in authentic flavor and packed with natural nutrients.",
    uses: "A versatile ingredient perfect for elevating your daily meals, baking, or enjoying straight from the source.",
    data: "Certified Organic • Ethically Sourced • No Added Preservatives • Nutrient Dense",
    whyToUse: "We work directly with farmers to ensure fair trade practices while bringing you the highest quality, unadulterated ingredients that taste better and are better for you.",
    howToUse: "Store in a cool, dry place. Use as desired in your favorite recipes to add a touch of premium, natural flavor.",
  },
  {
    id: "f10",
    name: "Artisan Coffee Beans",
    price: 22.0,
    category: "food",
    imageUrl: "/images/food_coffee_beans.png",
    boughtLastMonth: 4159,
    isTrending: false,
    isRecommended: true,
    description: "Our Artisan Coffee Beans is a culinary delight, sourced from the finest ethical farms around the globe. Rich in authentic flavor and packed with natural nutrients.",
    uses: "A versatile ingredient perfect for elevating your daily meals, baking, or enjoying straight from the source.",
    data: "Certified Organic • Ethically Sourced • No Added Preservatives • Nutrient Dense",
    whyToUse: "We work directly with farmers to ensure fair trade practices while bringing you the highest quality, unadulterated ingredients that taste better and are better for you.",
    howToUse: "Store in a cool, dry place. Use as desired in your favorite recipes to add a touch of premium, natural flavor.",
  },
  {
    id: "t1",
    name: "Handwoven Silk Saree",
    price: 120.0,
    category: "textiles",
    imageUrl: "/images/textiles_saree.png",
    boughtLastMonth: 2239,
    isTrending: false,
    isRecommended: false,
    description: "The Handwoven Silk Saree is a masterpiece of craftsmanship, woven by skilled artisans using generations-old techniques and premium natural fibers.",
    uses: "A timeless addition to your wardrobe or home decor, offering both unparalleled comfort and elegant style.",
    data: "100% Natural Fibers • Artisan Crafted • Ethically Made • Eco-Friendly Dyes",
    whyToUse: "By choosing this piece, you support sustainable fashion and artisan communities while enjoying a product that grows softer and more beautiful with age.",
    howToUse: "Dry clean or hand wash gently in cold water with mild detergent. Avoid direct sunlight when drying to preserve the natural dye colors.",
  },
  {
    id: "t2",
    name: "Cotton Block Print Scarf",
    price: 28.0,
    category: "textiles",
    imageUrl: "/images/textiles_scarf.png",
    boughtLastMonth: 1406,
    isTrending: false,
    isRecommended: false,
    description: "The Cotton Block Print Scarf is a masterpiece of craftsmanship, woven by skilled artisans using generations-old techniques and premium natural fibers.",
    uses: "A timeless addition to your wardrobe or home decor, offering both unparalleled comfort and elegant style.",
    data: "100% Natural Fibers • Artisan Crafted • Ethically Made • Eco-Friendly Dyes",
    whyToUse: "By choosing this piece, you support sustainable fashion and artisan communities while enjoying a product that grows softer and more beautiful with age.",
    howToUse: "Dry clean or hand wash gently in cold water with mild detergent. Avoid direct sunlight when drying to preserve the natural dye colors.",
  },
  {
    id: "t3",
    name: "Cashmere Winter Shawl",
    price: 185.0,
    category: "textiles",
    imageUrl: "/images/textiles_cashmere_shawl.png",
    boughtLastMonth: 549,
    isTrending: true,
    isRecommended: true,
    description: "The Cashmere Winter Shawl is a masterpiece of craftsmanship, woven by skilled artisans using generations-old techniques and premium natural fibers.",
    uses: "A timeless addition to your wardrobe or home decor, offering both unparalleled comfort and elegant style.",
    data: "100% Natural Fibers • Artisan Crafted • Ethically Made • Eco-Friendly Dyes",
    whyToUse: "By choosing this piece, you support sustainable fashion and artisan communities while enjoying a product that grows softer and more beautiful with age.",
    howToUse: "Dry clean or hand wash gently in cold water with mild detergent. Avoid direct sunlight when drying to preserve the natural dye colors.",
  },
  {
    id: "t4",
    name: "Linen Summer Tunic",
    price: 65.0,
    category: "textiles",
    imageUrl: "/images/textiles_linen_tunic.png",
    boughtLastMonth: 2628,
    isTrending: true,
    isRecommended: false,
    description: "The Linen Summer Tunic is a masterpiece of craftsmanship, woven by skilled artisans using generations-old techniques and premium natural fibers.",
    uses: "A timeless addition to your wardrobe or home decor, offering both unparalleled comfort and elegant style.",
    data: "100% Natural Fibers • Artisan Crafted • Ethically Made • Eco-Friendly Dyes",
    whyToUse: "By choosing this piece, you support sustainable fashion and artisan communities while enjoying a product that grows softer and more beautiful with age.",
    howToUse: "Dry clean or hand wash gently in cold water with mild detergent. Avoid direct sunlight when drying to preserve the natural dye colors.",
  },
  {
    id: "t5",
    name: "Embroidered Throw Pillow",
    price: 42.0,
    category: "textiles",
    imageUrl: "/images/textiles_throw_pillow.png",
    boughtLastMonth: 1805,
    isTrending: false,
    isRecommended: false,
    description: "The Embroidered Throw Pillow is a masterpiece of craftsmanship, woven by skilled artisans using generations-old techniques and premium natural fibers.",
    uses: "A timeless addition to your wardrobe or home decor, offering both unparalleled comfort and elegant style.",
    data: "100% Natural Fibers • Artisan Crafted • Ethically Made • Eco-Friendly Dyes",
    whyToUse: "By choosing this piece, you support sustainable fashion and artisan communities while enjoying a product that grows softer and more beautiful with age.",
    howToUse: "Dry clean or hand wash gently in cold water with mild detergent. Avoid direct sunlight when drying to preserve the natural dye colors.",
  },
  {
    id: "t6",
    name: "Organic Cotton Towel Set",
    price: 55.0,
    category: "textiles",
    imageUrl: "/images/textiles_towel_set.png",
    boughtLastMonth: 3903,
    isTrending: false,
    isRecommended: true,
    description: "The Organic Cotton Towel Set is a masterpiece of craftsmanship, woven by skilled artisans using generations-old techniques and premium natural fibers.",
    uses: "A timeless addition to your wardrobe or home decor, offering both unparalleled comfort and elegant style.",
    data: "100% Natural Fibers • Artisan Crafted • Ethically Made • Eco-Friendly Dyes",
    whyToUse: "By choosing this piece, you support sustainable fashion and artisan communities while enjoying a product that grows softer and more beautiful with age.",
    howToUse: "Dry clean or hand wash gently in cold water with mild detergent. Avoid direct sunlight when drying to preserve the natural dye colors.",
  },
  {
    id: "t7",
    name: "Hand-Dyed Indigo Throw",
    price: 85.0,
    category: "textiles",
    imageUrl: "/images/textiles_indigo_throw.png",
    boughtLastMonth: 3835,
    isTrending: true,
    isRecommended: false,
    description: "The Hand-Dyed Indigo Throw is a masterpiece of craftsmanship, woven by skilled artisans using generations-old techniques and premium natural fibers.",
    uses: "A timeless addition to your wardrobe or home decor, offering both unparalleled comfort and elegant style.",
    data: "100% Natural Fibers • Artisan Crafted • Ethically Made • Eco-Friendly Dyes",
    whyToUse: "By choosing this piece, you support sustainable fashion and artisan communities while enjoying a product that grows softer and more beautiful with age.",
    howToUse: "Dry clean or hand wash gently in cold water with mild detergent. Avoid direct sunlight when drying to preserve the natural dye colors.",
  },
  {
    id: "t8",
    name: "Bamboo Bed Sheets",
    price: 140.0,
    category: "textiles",
    imageUrl: "/images/textiles_bamboo_sheets.png",
    boughtLastMonth: 2394,
    isTrending: false,
    isRecommended: true,
    description: "The Bamboo Bed Sheets is a masterpiece of craftsmanship, woven by skilled artisans using generations-old techniques and premium natural fibers.",
    uses: "A timeless addition to your wardrobe or home decor, offering both unparalleled comfort and elegant style.",
    data: "100% Natural Fibers • Artisan Crafted • Ethically Made • Eco-Friendly Dyes",
    whyToUse: "By choosing this piece, you support sustainable fashion and artisan communities while enjoying a product that grows softer and more beautiful with age.",
    howToUse: "Dry clean or hand wash gently in cold water with mild detergent. Avoid direct sunlight when drying to preserve the natural dye colors.",
  },
  {
    id: "t9",
    name: "Woven Jute Rug",
    price: 110.0,
    category: "textiles",
    imageUrl: "/images/textiles_jute_rug.png",
    boughtLastMonth: 3069,
    isTrending: false,
    isRecommended: false,
    description: "The Woven Jute Rug is a masterpiece of craftsmanship, woven by skilled artisans using generations-old techniques and premium natural fibers.",
    uses: "A timeless addition to your wardrobe or home decor, offering both unparalleled comfort and elegant style.",
    data: "100% Natural Fibers • Artisan Crafted • Ethically Made • Eco-Friendly Dyes",
    whyToUse: "By choosing this piece, you support sustainable fashion and artisan communities while enjoying a product that grows softer and more beautiful with age.",
    howToUse: "Dry clean or hand wash gently in cold water with mild detergent. Avoid direct sunlight when drying to preserve the natural dye colors.",
  },
  {
    id: "t10",
    name: "Velvet Evening Wrap",
    price: 95.0,
    category: "textiles",
    imageUrl: "/images/textiles_velvet_wrap.png",
    boughtLastMonth: 3306,
    isTrending: false,
    isRecommended: true,
    description: "The Velvet Evening Wrap is a masterpiece of craftsmanship, woven by skilled artisans using generations-old techniques and premium natural fibers.",
    uses: "A timeless addition to your wardrobe or home decor, offering both unparalleled comfort and elegant style.",
    data: "100% Natural Fibers • Artisan Crafted • Ethically Made • Eco-Friendly Dyes",
    whyToUse: "By choosing this piece, you support sustainable fashion and artisan communities while enjoying a product that grows softer and more beautiful with age.",
    howToUse: "Dry clean or hand wash gently in cold water with mild detergent. Avoid direct sunlight when drying to preserve the natural dye colors.",
  }
];
